// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_5P4qMZ6vBJ5_c_0ohxi8WW7zFqTM2Fc',
    appId: '1:201348630370:web:1c35589227f92ec0e3ce3b',
    messagingSenderId: '201348630370',
    projectId: 'zoom-clone-b8c36',
    authDomain: 'zoom-clone-b8c36.firebaseapp.com',
    storageBucket: 'zoom-clone-b8c36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfEopmKXm3rNynFPW3uIZQP4oIlTzSs1Y',
    appId: '1:201348630370:android:fe2c7efb9ee5bc47e3ce3b',
    messagingSenderId: '201348630370',
    projectId: 'zoom-clone-b8c36',
    storageBucket: 'zoom-clone-b8c36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ5rB7UQvPQxLthUTEMa0JbiqXU9StwBk',
    appId: '1:201348630370:ios:9fa4a10b0faf8002e3ce3b',
    messagingSenderId: '201348630370',
    projectId: 'zoom-clone-b8c36',
    storageBucket: 'zoom-clone-b8c36.appspot.com',
    androidClientId: '201348630370-hiku6aashu5c3saq094p9ln763kv3l1t.apps.googleusercontent.com',
    iosClientId: '201348630370-qqe1gsre774v1po8ro9fen56p3pu8ooq.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ5rB7UQvPQxLthUTEMa0JbiqXU9StwBk',
    appId: '1:201348630370:ios:9fa4a10b0faf8002e3ce3b',
    messagingSenderId: '201348630370',
    projectId: 'zoom-clone-b8c36',
    storageBucket: 'zoom-clone-b8c36.appspot.com',
    androidClientId: '201348630370-hiku6aashu5c3saq094p9ln763kv3l1t.apps.googleusercontent.com',
    iosClientId: '201348630370-qqe1gsre774v1po8ro9fen56p3pu8ooq.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone101',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_5P4qMZ6vBJ5_c_0ohxi8WW7zFqTM2Fc',
    appId: '1:201348630370:web:558fa9b5e6853a62e3ce3b',
    messagingSenderId: '201348630370',
    projectId: 'zoom-clone-b8c36',
    authDomain: 'zoom-clone-b8c36.firebaseapp.com',
    storageBucket: 'zoom-clone-b8c36.appspot.com',
  );

}